### ISSUE TITLE
Add notice about licensing in wiki: it's not open source, it's copyrighted

### ISSUE THREAD

**Issue by Yolijn** [wesaynih/frameless#18]

**Comment by robbert** [comment]
> Frameless is not open source. It's copyrighted and all rights are reserved, like a book.

> Currently we're publicly putting the pieces back together, moving from a six years old 5000 commit Mercurial repository to a fresh Git repository. This time around we aim to have very strict continuous integration and unit test standards.

![screen shot 2016-05-01 at 13 51 23](https://cloud.githubusercontent.com/assets/30694/14941661/e256c372-0fa3-11e6-8ea7-cb68a232f4ac.png)
