### ISSUE TITLE
Add .editorconfig to maintain indentation standards across file types

### ISSUE THREAD

**Issue by robbert** [wesaynih/frameless#5]
- [x] `Add .editorconfig` with our preferences
- [x] Add continuous integration
- [ ] Ignore JSDoc comments

**Comment by robbert** [comment]
Unfortunately `eclint` complains about completely valid indentation of JSDoc comments:

```
file.js: line 2: invalid indent size: 1, expected: 4
file.js: line 3: invalid indent size: 1, expected: 4
```

For example:

```js
/**
 * @return {number}
 */
function test() {};
```

**Comment by robbert** [comment]
An issue was raised in the `eclint` repository already, specifically about this issue with JSDoc comments. [The reaction](https://github.com/jedmao/eclint/pull/36#issuecomment-155925547) was: "Honestly, I don't even use eclint myself any more."

Continue using `eclint` therefore doesn't seem a viable option anymore. An alternative package was suggested in the comments: [`lintespaces`](https://www.npmjs.com/package/lintspaces). That package in fact supports ignoring comments in different programming languages.

**Comment by robbert** [comment]
`lintspaces` indeed turns out to be an excellent package for this, and it was easy to configure it to ignore JSDoc comments. I'm using the [`gulp-lintspaces`](https://www.npmjs.com/package/gulp-lintspaces) because it nicely manages the reporting of warnings.

**Comment by robbert** [comment]
Just ran across the [`.gitignore` file in the lodash repository](https://github.com/lodash/lodash/blob/master/.gitattributes): it simply said `* text=auto`. [It turns out](http://stackoverflow.com/questions/21472971/what-is-the-purpose-of-text-auto-in-gitattributes-file) this is a builtin method to make sure LINE FEED U+00A0 is used everywhere as newline. We should use this too, this way we don't depend on developers having an EditorConfig plugin installed.

**Comment by robbert** [comment]
Added the `.gitattributes` file in commit e864670a0fa65b6db3a2dcad2b104a2e09b19084.

**Comment by Robbert** [comment]
Even with JavaScript comments ignored, there are too many false positives in my code to be useful for blocking commits based on lint results. I'm leaning towards validating indentation only for the very simplest of syntaxes, such as `.htaccess`.
